title: Traverso’s Restaurant
description: "Traverso's Naperville - Italian Family Restaurant, Lounge, and Pizzeria"
url: "http://traversosrestaurant.com"

destination: public
exclude: [public, Rakefile, README.md]

permalink: /writing/:title/
markdown: kramdown
highlighter: pygments

sass:
  style:    :compressed
  sass_dir: assets/stylesheets
